# docker-compose.yml
version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: gts_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gts
      POSTGRES_PASSWORD: gtspass
      POSTGRES_DB: gtsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
